config/routes.rb
Blog::Application.routes.draw do
  root "posts#index"
  resources :posts

  

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  embeds_many :comments

  field :title, type: String
  field :body, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.desc(:created_at)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BigGillyStyle</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">BigGillyStyle</a>
      <ul class="nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span9">
      <%= yield %>
    </div>
    <div class="span3">
      <section>
        <%= image_tag "andy.jpg", size: "150x150" %>
        <h4>Andy Pickler</h4>
        <article>
          <p>Ruby on Rails, Groovy/Grails, Java, Solr Developer</p>
          <p><a href="http://www.linkedin.com/in/andypickler">LinkedIn</a></p>
        </article>
      </section>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">My Rails 4 and MongoDB powered blog.  View the</a>
      <ul class="nav">
        <li class="active"><a href="https://github.com/BigGillyStyle/blog">source on Github</a>.</li>
      </ul>
    </div>
  </div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<section>
  <%= image_tag "andy.jpg", size: "150x150" %>
  <h3>Andy Pickler</h3>
  <article>
    <p>Ruby on Rails, Groovy/Grails, Java, Solr Developer</p>
    <p><a href="http://www.linkedin.com/in/andypickler">LinkedIn</a></p>
  </article>
</section>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <p><%= Time.zone.utc_to_local(post.created_at).to_formatted_s(:long) %></p>
  <p><%= post.body.truncate(50, separator: ' ', omission: '... (continued)') %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.title %></h2>
<p><%= Time.zone.utc_to_local(@post.created_at).to_formatted_s(:long) %></p>
<p><%= @post.body %></p>

<%= link_to 'Back', posts_path %>